### ISSUE TITLE
How to open data files

### ISSUE THREAD

**Issue by MJ-Zeng** [HelloJocelynLu/t5chem#11]
Hi,I want to view the content of the data file locally, is there any way to open it?
![image](https://user-images.githubusercontent.com/38970840/192207866-4276dbb8-7d11-4488-871c-6d21189f5982.png)

**Comment by HelloJocelynLu** [comment]
Hi,
The downloaded data files are zipped, you will need to extract them before using. Also see #9 
```
tar -xjvf <your file here>
```
