### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by soap117** [HelloJocelynLu/t5chem#14]
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV) when load from the pretrained file

**Comment by HelloJocelynLu** [comment]
Hi,

I never encounter this error. Can you provide more information about which system you are using & any other error messages (if you have) & the commands you have been used to load pretrained models?

Best,
Jocelyn

**Comment by tkella47** [comment]
My understanding is that this is a C like SegFault error. Usually comes from using the wrong cuda/ubuntu version or more likely, a f ile that is already open in a RW state is being modified but is locked due to the open state.  But as Jocelyn said, more info may be required...

**Comment by HelloJocelynLu** [comment]
> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV) when load from the pretrained file

Hi, any updates?

**Comment by soap117** [comment]
Reinstall the environment, the problem is solved.

**Comment by HelloJocelynLu** [comment]
> Reinstall the environment, the problem is solved.

Good to know! Thanks.
