### ISSUE TITLE
Dataset damage

### ISSUE THREAD

**Issue by WangYitian123** [HelloJocelynLu/t5chem#19]
Hi,
I downloaded the dataset from https://yzhang.hpc.nyu.edu/T5Chem/index.html. For USPTO_500_MT and USPTO_TPL dataset, I cannot open them correctly. However, for other dataset, such as USPTO-MIT, it worked.   

Thanks a lot.

**Comment by WangYitian123** [comment]
Could you please tell me the correct encoding format for these files and what should be used to open them?

**Comment by HelloJocelynLu** [comment]
Hi,

Thank you for the report. I suspect an issue with the webpage download links (which I will address soon! Appreciate the heads-up). Here's the usual process I followed:

Step 1: Copy the download link of the dataset you're interested in.
Step 2: Download the dataset:
```bash
wget https://yzhang.hpc.nyu.edu/T5Chem/data/USPTO_500_MT.tar.bz2
```
Step 3: Unpack the compressed file:
```
tar -xvf USPTO_500_MT.tar.bz2
```
Here's what I found on MacOS:
<img width="701" alt="image" src="https://github.com/HelloJocelynLu/t5chem/assets/34988596/6a06f89e-ac44-4c3f-a8d4-7e5184a1f13b">

I hope this information is useful!

**Comment by WangYitian123** [comment]
Hi,


Thanks a lot. You are so nice.&nbsp;I have solved the problem and the&nbsp;webpage download links are correct.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月14日(星期五) 下午4:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [HelloJocelynLu/t5chem] Dataset damage (Issue #19)














 
Hi,
 
Thank you for the report. I suspect an issue with the webpage download links (which I will address soon! Appreciate the heads-up). Here's the usual process I followed:
 
Step 1: Copy the download link of the dataset you're interested in.
 Step 2: Download the dataset:
 wget https://yzhang.hpc.nyu.edu/T5Chem/data/USPTO_500_MT.tar.bz2
 
Step 3: Unpack the compressed file:
 tar -xvf USPTO_500_MT.tar.bz2  
Here's what I found on MacOS:
 image.png (view on web)
 
I hope this information is useful!
