### ISSUE TITLE
data downloading error

### ISSUE THREAD

**Issue by zhaisilong** [HelloJocelynLu/t5chem#2]
position site: <https://yzhang.hpc.nyu.edu/T5Chem/index.html>

Problem:USPTO_MIT data not fond

Reason: <https://yzhang.hpc.nyu.edu/T5Chem/data/USPTO_MIT.tar.tar.bz2> Link error. It should be `USPTO_MIT.tar.bz2`

**Comment by HelloJocelynLu** [comment]
Hi, 

Thank you for reporting this! It should be fixed now. Please check.

Jocelyn
