### ISSUE TITLE
我怎么运行这个t5chem

### ISSUE THREAD

**Issue by festla** [HelloJocelynLu/t5chem#21]
我已经下载了文件，接下来该做什么，有什么需要安装的依赖，我该在哪个接口运行；有没有简洁的步骤

**Comment by HelloJocelynLu** [comment]
您好，请查阅首页 读我 说明：https://github.com/HelloJocelynLu/t5chem
推荐使用docker镜像，减少环境配置的麻烦。
如果您想自己搭建环境，或者在使用colab的过程中遇到了麻烦，可以参考：https://github.com/HelloJocelynLu/t5chem/issues/17
数据和与训练的模型下载：https://yzhang.hpc.nyu.edu/T5Chem/index.html
使用教程：https://yzhang.hpc.nyu.edu/T5Chem/tutorial.html

**Comment by HelloJocelynLu** [comment]
Hi 请问你解决了这个问题吗

**Comment by festla** [comment]
感谢您的回复，我当时看的第一篇关于这个方向的论文就是t5chem；但当我想要更进一步复现这篇论文时，才发现自己还缺少很多基础方面的知识（尤其是有关深度学习及代码的知识。由于我本科学习的是化学专业，故而缺少很多编程的实践，自学时不免抓不住重点）。


我也尝试直接去读经典的论文，如transformer等；但即便是看着github上的代码，想要实现时却又无从下手；网上有从0开始实现transformer的视频教程，对于其中矩阵维数对应又会让我很困惑（我总是想把这些问题对应到学习线性代数的问题，在线性代数中矩阵的行列有具象的定义，在这方面是否需要花费精力来完全在纸上推导完成（Python中的行列有时会让我很迷惑））。


您能否给我分享一些您在入门过程中都遇到过什么问题，您如何解决；希望您能为我提供一些有关入门的学习方法。


期待您的回复！


------------------------
刘千龙&nbsp; &nbsp; &nbsp;硕士研究生
湘潭大学&nbsp; 计算机学院&nbsp;&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "HelloJocelynLu/t5chem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月22日(星期五) 下午2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HelloJocelynLu/t5chem] 我怎么运行这个t5chem (Issue #21)





 
Hi 请问你解决了这个问题吗

**Comment by HelloJocelynLu** [comment]
您好，

我个人觉得初学的话，还是不要一开始钻到比较细分的领域里。按照描述如果您的背景是实验化学的话，可以先从编程基础开始。
总的来说，学习路径大概是：python编程基础 - 科学计算相关的包 - 机器学习/深度学习理论知识 - 化学信息学工具 - 结合化学信息学和简单机器学习的实践 - 训练一个神经网络的实践（不一定要是化学问题）- 特定的神经网络（取决于你对什么方向感兴趣）
  * 先掌握Python基础编程 （可以看youtube或者B站之类的，很多资源）
  * 学习NumPy，sklearn等科学计算库的基础操作（看文档吧，如https://scikit-learn.org/stable/ ）
  * 理解深度学习基础概念（如Andrew Ng的课程）
  * rdkit最常用的化学信息学包，要熟悉一下（[notebook](https://github.com/rdkit/rdkit-tutorials/tree/master/notebooks)，[document](https://www.rdkit.org/docs/GettingStartedInPython.html)，我自己也写过一个[tutorial](https://gist.github.com/HelloJocelynLu/f115fc1624730da7f045a60095976ea4#file-rdkit_workshop-ipynb)）
  * 结合化学信息学和简单机器学习的实践，如用morgan fingerprint预测能量、溶解度、蛋白质小分子结合能、反应产率等，例子很多一搜便是不一一赘述。e.g.： https://tianchi.aliyun.com/notebook/757882
  * 从简单的神经网络开始实践（如[pytorch](https://pytorch.org/tutorials/beginner/basics/intro.html)文档）
  * 最后再逐步过渡到Transformer等复杂模型

工具上建议使用conda管理环境，用vscode（或者其他IDE）写代码，初学时用jupyter notebook可视化图形表格等

直接看一篇论文以及代码实现确实会比较困难。而且心态上先不要深挖算法背后的数学理论，可以以先用起来为目标。

考虑到这些问题的讨论超出了此issue的范畴，我这边先关闭了。如果有需要可以邮件联系。

**Comment by festla** [comment]
感谢您分享的路线。有了这些指导给我提供很大的帮助，能够避免我在学习过程中遇到困难就会迷失方向而很急躁。
我会尝试这些教程，并在有所收获后一定e-mail给您反馈。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HelloJocelynLu/t5chem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月22日(星期五) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HelloJocelynLu/t5chem] 我怎么运行这个t5chem (Issue #21)





 
您好，
 
我个人觉得初学的话，还是不要一开始钻到比较细分的领域里。按照描述如果您的背景是实验化学的话，可以先从编程基础开始。
 总的来说，学习路径大概是：python编程基础 - 科学计算相关的包 - 机器学习/深度学习理论知识 - 化学信息学工具 - 结合化学信息学和简单机器学习的实践 - 训练一个神经网络的实践（不一定要是化学问题）- 特定的神经网络（取决于你对什么方向感兴趣）
  
先掌握Python基础编程 （可以看youtube或者B站之类的，很多资源）
 
学习NumPy，sklearn等科学计算库的基础操作（看文档吧，如https://scikit-learn.org/stable/ ）
 
理解深度学习基础概念（如Andrew Ng的课程）
 
rdkit最常用的化学信息学包，要熟悉一下（notebook，document，我自己也写过一个tutorial）
 
结合化学信息学和简单机器学习的实践，如用morgan fingerprint预测能量、溶解度、蛋白质小分子结合能、反应产率等，例子很多一搜便是不一一赘述。e.g.： https://tianchi.aliyun.com/notebook/757882
 
从简单的神经网络开始实践（如pytorch文档）
 
最后再逐步过渡到Transformer等复杂模型
  
工具上建议使用conda管理环境，用vscode（或者其他IDE）写代码，初学时用jupyter notebook可视化图形表格等
 
直接看一篇论文以及代码实现确实会比较困难。而且心态上先不要深挖算法背后的数学理论，可以以先用起来为目标。
 
考虑到这些问题的讨论超出了此issue的范畴，我这边先关闭了。如果有需要可以邮件联系。
