### ISSUE TITLE
'utf-8' codec can't decode vocab.pt in pretrain models

### ISSUE THREAD

**Issue by Youzhuqinghuan** [HelloJocelynLu/t5chem#23]
When I use pretrain models like `USPTO_MT_model.tar.bz2` or `simple_pretrain.tar.bz2`, it occurs that:
```
Traceback (most recent call last):
  File "/home/hcp/Chem/t5chem/test.py", line 6, in <module>
    tokenizer = SimpleTokenizer(vocab_file=os.path.join(pretrain_path, 'vocab.pt'))
  File "/home/hcp/Chem/t5chem/t5chem/mol_tokenizers.py", line 204, in __init__
    super().__init__(vocab_file=vocab_file, max_size=max_size, **kwargs)
  File "/home/hcp/Chem/t5chem/t5chem/mol_tokenizers.py", line 75, in __init__
    self.create_vocab(vocab_file=vocab_file)
  File "/home/hcp/Chem/t5chem/t5chem/mol_tokenizers.py", line 101, in create_vocab
    self.vocab: Vocab = Vocab.load(vocab_file)
  File "/home/hcp/Chem/t5chem/t5chem/mol_tokenizers.py", line 51, in load
    tokens = [line.strip() for line in f]
  File "/home/hcp/Chem/t5chem/t5chem/mol_tokenizers.py", line 51, in <listcomp>
    tokens = [line.strip() for line in f]
  File "/home/hcp/miniconda3/envs/t5chem/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
```
Looking for your reply!

**Comment by Youzhuqinghuan** [comment]
And it seems that `vocab.pt` cannot be used in `train --data_dir data/sample/regression/ --output_dir model/ --task_type regression --pretrain ./pretrain_model/pretrain/simple`.It occurs that:
```
Namespace(data_dir='data/sample/regression/', output_dir='model/', task_type='regression', run_name='', pretrain='./pretrain_model/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=100, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=None, command=<function train at 0x7f5e65edbb80>)
Some weights of T5ForProperty were not initialized from the model checkpoint at ./pretrain_model/pretrain/simple and are newly initialized because the shapes did not match:
- lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/hcp/miniconda3/envs/t5chem/bin/t5chem", line 8, in <module>
    sys.exit(main())
  File "/home/hcp/miniconda3/envs/t5chem/lib/python3.9/site-packages/t5chem/__main__.py", line 33, in main
    command(args)
  File "/home/hcp/miniconda3/envs/t5chem/lib/python3.9/site-packages/t5chem/run_trainer.py", line 146, in train
    raise ValueError(
ValueError: Can't find a vocabulary file at path './pretrain_model/pretrain/simple'.
```

**Comment by HelloJocelynLu** [comment]
> When I use pretrain models like `USPTO_MT_model.tar.bz2` or `simple_pretrain.tar.bz2`, it occurs that:
> 
> ```
> Traceback (most recent call last):
>   File "/home/hcp/Chem/t5chem/test.py", line 6, in <module>
>     tokenizer = SimpleTokenizer(vocab_file=os.path.join(pretrain_path, 'vocab.pt'))
>   File "/home/hcp/Chem/t5chem/t5chem/mol_tokenizers.py", line 204, in __init__
>     super().__init__(vocab_file=vocab_file, max_size=max_size, **kwargs)
>   File "/home/hcp/Chem/t5chem/t5chem/mol_tokenizers.py", line 75, in __init__
>     self.create_vocab(vocab_file=vocab_file)
>   File "/home/hcp/Chem/t5chem/t5chem/mol_tokenizers.py", line 101, in create_vocab
>     self.vocab: Vocab = Vocab.load(vocab_file)
>   File "/home/hcp/Chem/t5chem/t5chem/mol_tokenizers.py", line 51, in load
>     tokens = [line.strip() for line in f]
>   File "/home/hcp/Chem/t5chem/t5chem/mol_tokenizers.py", line 51, in <listcomp>
>     tokens = [line.strip() for line in f]
>   File "/home/hcp/miniconda3/envs/t5chem/lib/python3.9/codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
> ```
> 
> Looking for your reply!

Hi, I just updated this repo and now it loads plain text rather than *.pt file, you may need to `git pull` the lastest commits (make sure you have 1.2.0 version).

**Comment by HelloJocelynLu** [comment]
> And it seems that `vocab.pt` cannot be used in `train --data_dir data/sample/regression/ --output_dir model/ --task_type regression --pretrain ./pretrain_model/pretrain/simple`.It occurs that:
> 
> ```
> Namespace(data_dir='data/sample/regression/', output_dir='model/', task_type='regression', run_name='', pretrain='./pretrain_model/pretrain/simple', vocab='', tokenizer='', random_seed=8570, num_epoch=100, eval_steps=5000, log_step=1000, batch_size=32, init_lr=0.0005, num_classes=None, command=<function train at 0x7f5e65edbb80>)
> Some weights of T5ForProperty were not initialized from the model checkpoint at ./pretrain_model/pretrain/simple and are newly initialized because the shapes did not match:
> - lm_head.weight: found shape torch.Size([100, 256]) in the checkpoint and torch.Size([2, 256]) in the model instantiated
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> Traceback (most recent call last):
>   File "/home/hcp/miniconda3/envs/t5chem/bin/t5chem", line 8, in <module>
>     sys.exit(main())
>   File "/home/hcp/miniconda3/envs/t5chem/lib/python3.9/site-packages/t5chem/__main__.py", line 33, in main
>     command(args)
>   File "/home/hcp/miniconda3/envs/t5chem/lib/python3.9/site-packages/t5chem/run_trainer.py", line 146, in train
>     raise ValueError(
> ValueError: Can't find a vocabulary file at path './pretrain_model/pretrain/simple'.
> ```

Thank you for catching this issue! The vocab.pt file in the old compressed file is incompatible with the current code version. I've notified the website administrator to update the model weights file, though this may take some time. In the meantime, please try [this](https://github.com/HelloJocelynLu/t5chem/pull/22#issue-2705204870) workaround: 
replace the old .pt file with the .txt file using the following command:
```bash
cp t5chem/vocab/simple.txt models/pretrain/simple/vocab.txt
```

**Comment by HelloJocelynLu** [comment]
This is what I did starting from a fresh new machine:
```bash
pip install t5chem --index-url https://pypi.org/project/
wget https://yzhang.hpc.nyu.edu/T5Chem/data/sample_data.tar.bz2
wget https://yzhang.hpc.nyu.edu/T5Chem/models/simple_pretrain.tar.bz2
tar -xjvf sample_data.tar.bz2
tar -xjvf simple_pretrain.tar.bz2

wget https://raw.githubusercontent.com/HelloJocelynLu/t5chem/refs/heads/main/t5chem/vocab/simple.txt
cp simple.txt models/pretrain/simple/vocab.txt

t5chem train --data_dir data/sample/regression/ --output_dir model/ --task_type regression --pretrain models/pretrain/simple
t5chem predict --data_dir data/sample/regression/ --model_dir model/ 
```
Then this is what I got:
<img width="1177" alt="image" src="https://github.com/user-attachments/assets/319b0062-8369-4868-8e48-274615fa3bfa">

**Comment by Youzhuqinghuan** [comment]
> This is what I did starting from a fresh new machine:

Thank you very much for your reply! You are the most prompt author I have ever encountered in handling issues!XD I have tried the content of your previous response, and I am now able to start training and making predictions. Thank you for your assistance, and I wish you a successful scientific research journey!
