### ISSUE TITLE
USPTO_500_MT miss '334' in the 'labels' column?

### ISSUE THREAD

**Issue by DaShenZi721** [HelloJocelynLu/t5chem#5]
I found there are 499 labels without '334'(i.e. [0, 1, ... 333, 335, ... 498, 499]) in the 'labels' column of the dataset USPTO_500_MT.
Is it correct?

**Comment by HelloJocelynLu** [comment]
Hi,
It is correct. It is only a subset of original USPTO_1k_TPL after removing some sparse classes.
