### ISSUE TITLE
ModuleNotFoundError: No module named 'rdkit'

### ISSUE THREAD

**Issue by yxnyu** [HelloJocelynLu/t5chem#7]
The Colab environment seems that rdkit and transformer do not well perform

**Comment by HelloJocelynLu** [comment]
Based on the error message, it seems that rdkit is not successfully installed... rdkit is a pain for google colab. 
I will work on this.
Meanwhile, would you mind trying `condacolab`? I find an examples on installing rdkit [here](https://iwatobipen.wordpress.com/2018/11/01/run-rdkit-and-deep-learning-on-google-colab-rdkit/) and [here](https://colab.research.google.com/gist/iwatobipen/2ec7faeafe5974501e69fcc98c122922/pymol.ipynb#scrollTo=xIYbBtkjgEfU)

**Comment by yxnyu** [comment]
Dear Jocelyn

Yes. Sorry for responsing so later. I am trying to rebuild the rdkit in my
environment and I realize my supervisor permit the NYU-HPC account and I am
learning about the HPC knowledge while I just know how to use the server in
the group .

Condacolab is a new to me but I would like to use it. I will reach out to
you once the trying is done.

Best,
Yuzhi

**Comment by HelloJocelynLu** [comment]
Hi,
I've updated the google colabs and successfully ran it on Google cloud. Free feel to try it!

**Comment by yxnyu** [comment]
Dear Jocelyn

Awesome, thanks! I will try it, and I am in NYC taking the course and are
you still in the NYC?

Best,
Yuzhi

**Comment by HelloJocelynLu** [comment]
Hi Yuzhi,

I replied your message via email.

Best,
Jocelyn
