### ISSUE TITLE
About the (binary) datasets downloaded from the website

### ISSUE THREAD

**Issue by a09358872999** [HelloJocelynLu/t5chem#9]
How can I change the binary files(C_N_yield,USPTO_50k...) downloaded from the website to a file type readable(like txt files in data/data/sample) by the model.

**Comment by tkella47** [comment]
`tar -xjvf <your file here>`
a folder called data will be produced. It will contain human readable files and machine files.

**Comment by HelloJocelynLu** [comment]
Hi,

The downloaded files ([README](https://github.com/HelloJocelynLu/t5chem/tree/main/data)) are zipped. One will need to extract them as Thomas said.
Hope it helps!

Jocelyn

**Comment by a09358872999** [comment]
Thank you all for your warm help

After knowing that these are zip files(but w/o filename extension),it works.
